name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          [
            7.2,
            7.3,
            7.4,
            8.0,
            8.1,
          ]

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v1

      - name: prepare
        run: composer update

      - name: test
        run: composer test
